import sys, os
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from core.myabac import parse_abac_file
from acl_analyzer import compare_acl
from acl_generator import generate_acl
from api_functions.gemini_call import gemini_api_call
from api_functions.local_api import local_api_call
from helper_functions import append_from_file , clear_file, write_to_file



def main():
 
    # passes info from a .abac file into data sets
        # the arguement is an .abac file
        # input file 1: A complete .abac file
        # optional: run the following line to help create the ACL list,
            # we only need to generate our ground truth ACL list once per data set
            # should not be ran every itteration to save unecessary computations
            # TODO: comment out when not needed. 

    # user, res, rule = parse_abac_file("DATASETS/abac-datasets/healthcare.abac")


    #optional: can run to generate ground truth ACL list from an abac file if desired 
        # to save computations for testing this should not be ran every itteration
        # instead declare what ACL file you will be using ahead of testing (ground truth).
        # should have ABAC rules included.
        # input file 2: here we would declare where to save our ground truth ACL file to.
        # TODO: comment out when not needed. 

    # generate_acl(user, res, rule, "llm-research/ground-truth-ACL/healthcare-ACL.txt")

    #input file 3: declare which ACL file is the ground truth 
        # will be sent to LLM
    gt_acl_file = "llm-research/ground-truth-ACL/healthcare-ACL.txt"

    # input file 4: the attribute data policy description
        # will be sent to LLM
    policy_description_file ="DATASETS-for-LLM/healthcare/README.md"


    #input file 5: The abac policy file that will be sent to the LLM
        # does not include any rules, everything else is included.
    llm_abac_policy_file = "DATASETS-for-LLM/healthcare/healthcare.abac"



    # TODO: make a folder or something with only gt abac rules for every data set
    gt_abac_rules = " "


    # declare session files
    # store info on the session being ran
        # TODO: declare what info is needed 
    session_info = " "

    # The file in which the LLM response should be saved to, should be the ABAC rules
        # generated file 1:
    session_response = "llm-research/session/session-llm-response.txt"

    
    # A call to any API should be made here
    gemini_api_call(session_response, gt_acl_file, llm_abac_policy_file, policy_description_file)
    # local_api_call(abac_rules_generated, acl_file, attribute_data_file, attribute_description_file)

    # generated file 2: this file is a temporary file for each session, it allows us to build an ABAC file with 
        # the rules generated by the LLM
        # we need this file to generate an ACL list
    session_abac_file = "llm-research/session/session-abac.txt"

    # generated file 3: This file is where the llm's ACL list should be stored.
    llm_acl_file = "llm-research/session/session-ACL.txt"


    #clear the file to write in
    clear_file(session_abac_file)

    # write the abac policy (llm version that has no rules) into the session abac file
    append_from_file(session_abac_file, llm_abac_policy_file)

    # write the rules (generated by the LLM) intot the session abac file
    append_from_file(session_abac_file, session_response)

    # create abac data structures from the session abac file (the one generated with LLM abac rules)
    user2, res2, rule2 = parse_abac_file(session_abac_file)

    # make a new ACL using the rules given by the LLM
    generate_acl(user2, res2, rule2, llm_acl_file)

    # generated file 4: This file stores the comparison data between the ground truth acl and llm acl
    session_comparison_file  = "llm-research/session/session-comparison.txt"

    #store the comparison in a text object
    temp_text, temp_boolean = compare_acl(gt_acl_file,llm_acl_file)

    #write the comparison to a text file
    write_to_file(session_comparison_file, temp_text)
    



if __name__ == "__main__":
    main()
